type Zombie={x:number;y:number;hp:number;speed:number;kind:'walker'|'runner'|'brute';frame:number};
type Drop={x:number;y:number;kind:'xp'|'food'|'fuel'|'scrap';life:number};
const canvas=document.querySelector<HTMLCanvasElement>('#game')!;const ctx=canvas.getContext('2d')!;
const $=<T extends HTMLElement>(id:string)=>document.querySelector<T>(`#${id}`)!;
const ui={wave:$('wave'),level:$('level'),kills:$('kills'),food:$('food'),fuel:$('fuel'),scrap:$('scrap'),hp:$('hp'),hpFill:$('hp-fill'),xp:$('xp'),xpFill:$('xp-fill'),action:$('action'),epsilon:$('epsilon'),policy:$('policy'),status:$('status'),work:$('work')};
const sprite=new Image();sprite.src='/assets/zombie-survivor/zombie-files/png/male/Walk%20(1).png';
let w=innerWidth,h=innerHeight,previous=performance.now(),wave=1,level=1,xp=0,nextXp=10,kills=0,food=30,fuel=30,scrap=0,hp=100,maxHp=100,weapon=1,waveTime=0,workTime=0,workOpen=false,spawn=0,agentSteps=0;let zombies:Zombie[]=[];let drops:Drop[]=[];
const player={x:0,y:0,fire:0,vx:0,vy:0};let manualUntil=0,paused=false;const keys=new Set<string>();
addEventListener('keydown',event=>{keys.add(event.key.toLowerCase());if(event.key===' '){paused=!paused;ui.status.textContent=paused?'一時停止':'WAVE進行中 · 自律戦闘'}if(event.key.toLowerCase()==='q')weapon=Math.max(1,weapon-1);if(event.key.toLowerCase()==='e')weapon++});addEventListener('keyup',event=>keys.delete(event.key.toLowerCase()));
function resize(){w=innerWidth;h=innerHeight;const d=Math.min(devicePixelRatio,2);canvas.width=w*d;canvas.height=h*d;ctx.setTransform(d,0,0,d,0,0);player.x=w/2;player.y=h/2}addEventListener('resize',resize);resize();
function rand(a:number,b:number){return a+Math.random()*(b-a)}
function spawnZombie(){const angle=rand(0,Math.PI*2),radius=Math.max(w,h)*.62;const roll=Math.random();const kind=roll<.68?'walker':roll<.9?'runner':'brute';zombies.push({x:player.x+Math.cos(angle)*radius,y:player.y+Math.sin(angle)*radius,hp:kind==='brute'?5+wave*.3:kind==='runner'?2:1,speed:(kind==='runner'?48:kind==='brute'?20:30)+wave*.8,kind,frame:0})}
function agentAction(){agentSteps++;const nearest=zombies.reduce((a,b)=>Math.hypot(a.x-player.x,a.y-player.y)<Math.hypot(b.x-player.x,b.y-player.y)?a:b,zombies[0]);if(nearest&&Math.hypot(nearest.x-player.x,nearest.y-player.y)<120){ui.action.textContent='危険距離から離脱';return}ui.action.textContent=nearest?'最近接標的を射撃':'周辺を探索'}
function gainXp(amount:number){xp+=amount;while(xp>=nextXp){xp-=nextXp;level++;nextXp=Math.floor(nextXp*1.22);weapon++}}
function kill(z:Zombie){kills++;gainXp(z.kind==='brute'?5:1);scrap+=z.kind==='brute'?3:1;const r=Math.random();if(r<.15)drops.push({x:z.x,y:z.y,kind:'food',life:10});else if(r<.3)drops.push({x:z.x,y:z.y,kind:'fuel',life:10});}
function finishWave(){wave++;waveTime=0;food=Math.max(0,food-2);fuel=Math.max(0,fuel-2);workOpen=true;workTime=0;ui.work.classList.add('open');ui.status.textContent='作業タイム · 資源配分を判断中';ui.policy.textContent='作業'}
function doWork(kind:'food'|'fuel'|'repair'|'upgrade'){if(kind==='food'&&fuel>=2){fuel-=2;food+=10}else if(kind==='fuel'&&food>=2){food-=2;fuel+=10}else if(kind==='repair'&&scrap>=6){scrap-=6;hp=Math.min(maxHp,hp+35)}else if(kind==='upgrade'&&scrap>=10){scrap-=10;weapon++}else return;workOpen=false;ui.work.classList.remove('open');ui.status.textContent='WAVE進行中 · 自律戦闘';ui.policy.textContent='戦闘'}
document.querySelectorAll<HTMLButtonElement>('[data-work]').forEach(b=>b.onclick=()=>doWork(b.dataset.work as 'food'|'fuel'|'repair'|'upgrade'));
function autoWork(){if(food<10&&fuel>=2)return doWork('food');if(fuel<10&&food>=2)return doWork('fuel');if(hp<60&&scrap>=6)return doWork('repair');if(scrap>=10)return doWork('upgrade');workOpen=false;ui.work.classList.remove('open');ui.status.textContent='WAVE進行中 · 自律戦闘';ui.policy.textContent='戦闘'}
function update(dt:number){if(workOpen){workTime+=dt;if(workTime>3)autoWork();return}waveTime+=dt;spawn-=dt;if(spawn<=0){spawn=Math.max(.18,1.1-wave*.025);if(zombies.length<Math.min(70,12+wave*3))spawnZombie()}agentAction();player.fire-=dt;for(const z of zombies){const dx=player.x-z.x,dy=player.y-z.y,d=Math.hypot(dx,dy)||1;z.x+=dx/d*z.speed*dt;z.y+=dy/d*z.speed*dt;z.frame+=dt*8;if(d<24)hp-=dt*(z.kind==='brute'?8:2)}if(player.fire<=0&&zombies.length){player.fire=.38/Math.min(2,1+weapon*.08);const target=zombies.reduce((a,b)=>Math.hypot(a.x-player.x,a.y-player.y)<Math.hypot(b.x-player.x,b.y-player.y)?a:b);target.hp-=weapon; if(target.hp<=0){const idx=zombies.indexOf(target);zombies.splice(idx,1);kill(target);drops.push({x:target.x,y:target.y,kind:'xp',life:8})}}for(const d of drops){d.life-=dt;if(Math.hypot(d.x-player.x,d.y-player.y)<32){if(d.kind==='xp')gainXp(1);if(d.kind==='food')food++;if(d.kind==='fuel')fuel++;if(d.kind==='scrap')scrap++;d.life=0}}drops=drops.filter(d=>d.life>0);if(waveTime>35)finishWave();if(hp<=0){wave=1;level=1;xp=0;nextXp=10;hp=maxHp;zombies=[];drops=[];food=Math.max(10,food);fuel=Math.max(10,fuel);ui.status.textContent='再出撃 · エピソード終了'}}
function draw(){ctx.fillStyle='#111a17';ctx.fillRect(0,0,w,h);ctx.strokeStyle='#1e342b';ctx.lineWidth=1;for(let x=0;x<w;x+=48){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,h);ctx.stroke()}for(let y=0;y<h;y+=48){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(w,y);ctx.stroke()}ctx.fillStyle='#283c31';for(let i=0;i<18;i++){const x=(i*137+wave*19)%w,y=(i*83+wave*11)%h;ctx.fillRect(x,y,20,6)}for(const d of drops){ctx.fillStyle=d.kind==='xp'?'#ffd166':d.kind==='food'?'#6dff9d':d.kind==='fuel'?'#65c9ff':'#c58cff';ctx.beginPath();ctx.arc(d.x,d.y,5,0,Math.PI*2);ctx.fill()}for(const z of zombies){ctx.save();ctx.translate(z.x,z.y);ctx.fillStyle=z.kind==='runner'?'#e7b86b':z.kind==='brute'?'#b76c6c':'#73ad7e';ctx.beginPath();ctx.arc(0,0,z.kind==='brute'?16:11,0,Math.PI*2);ctx.fill();ctx.fillStyle='#162018';ctx.fillRect(-6,-3,3,3);ctx.fillRect(3,-3,3,3);ctx.restore()}ctx.fillStyle='#e5f7dc';ctx.beginPath();ctx.arc(player.x,player.y,15,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#ff526e';ctx.lineWidth=3;ctx.stroke();ctx.fillStyle='#ff526e';ctx.fillRect(player.x+12,player.y-3,30,6)}
function hud(){ui.wave.textContent=String(wave);ui.level.textContent=String(level);ui.kills.textContent=String(kills);ui.food.textContent=String(food);ui.fuel.textContent=String(fuel);ui.scrap.textContent=String(scrap);ui.hp.textContent=`${Math.max(0,Math.round(hp))} / ${maxHp}`;ui.hpFill.style.width=`${Math.max(0,hp/maxHp*100)}%`;ui.xp.textContent=`${xp} / ${nextXp}`;ui.xpFill.style.width=`${xp/nextXp*100}%`;ui.epsilon.textContent=`${Math.max(5,20-agentSteps/500).toFixed(0)}%`}
function drawAnimatedSprites(){if(!sprite.complete||!sprite.naturalWidth)return;const frames=5,frameWidth=sprite.naturalWidth/frames;ctx.imageSmoothingEnabled=false;for(const z of zombies){ctx.drawImage(sprite,Math.floor(z.frame)%frames*frameWidth,0,frameWidth,sprite.naturalHeight,z.x-18,z.y-22,36,44)}}
function frame(now:number){const dt=Math.min(.04,(now-previous)/1000);previous=now;update(dt);draw();drawAnimatedSprites();hud();requestAnimationFrame(frame)}requestAnimationFrame(frame);
