import type { Enemy, EnemyShot } from './gunship_enemies.js';
import type { GunshipBody, GunshipAction } from './gunship_physics.js';
import { SEA_Y, altitudeMargin } from './gunship_physics.js';

export function renderGunship(ctx: CanvasRenderingContext2D, width: number, height: number, ship: GunshipBody, action: GunshipAction, enemies: Enemy[], enemyShots: EnemyShot[], bullets: EnemyShot[], wave: number): void {
  const sx = width / 1200; const sy = height / 840; ctx.setTransform(sx, 0, 0, sy, 0, 0);
  const sky = ctx.createLinearGradient(0, 0, 0, 840); sky.addColorStop(0, '#63a9ce'); sky.addColorStop(.62, '#173d5a'); sky.addColorStop(1, '#06101d'); ctx.fillStyle = sky; ctx.fillRect(0, 0, 1200, 840);
  drawClouds(ctx);
  ctx.fillStyle = 'rgba(255,205,125,.16)'; ctx.beginPath(); ctx.arc(975, 105, 65, 0, Math.PI * 2); ctx.fill();
  ctx.fillStyle = '#08334d'; ctx.fillRect(0, SEA_Y, 1200, 50); ctx.strokeStyle = '#68cde7'; ctx.lineWidth = 3; ctx.beginPath(); for (let x = 0; x <= 1200; x += 12) { const y = SEA_Y + Math.sin(x * .04 + performance.now() * .002) * 4; x ? ctx.lineTo(x, y) : ctx.moveTo(x, y); } ctx.stroke();
  for (const enemy of enemies) drawEnemy(ctx, enemy);
  for (const shot of enemyShots) drawShot(ctx, shot, '#ff8964');
  for (const bullet of bullets) drawShot(ctx, bullet, '#e8f8a6');
  ctx.save(); ctx.translate(ship.x, ship.y); ctx.rotate(-ship.angle);
  if (action.thrust) { ctx.fillStyle = '#ffbd5a'; ctx.beginPath(); ctx.moveTo(-26, 0); ctx.lineTo(-55 - Math.random() * 18, -9); ctx.lineTo(-55 - Math.random() * 18, 9); ctx.closePath(); ctx.fill(); }
  ctx.fillStyle = '#d6eaf1'; ctx.strokeStyle = '#153442'; ctx.lineWidth = 3; ctx.beginPath(); ctx.moveTo(28, 0); ctx.lineTo(-22, -15); ctx.lineTo(-12, 0); ctx.lineTo(-22, 15); ctx.closePath(); ctx.fill(); ctx.stroke(); ctx.fillStyle = '#49d9eb'; ctx.fillRect(1, -6, 12, 12); ctx.restore();
  const danger = Math.max(0, 1 - altitudeMargin(ship) / 180); if (danger > 0) { ctx.fillStyle = `rgba(184,32,25,${danger * .35})`; ctx.fillRect(0, 0, 1200, 840); }
  if (ship.y > SEA_Y - 90 && ship.vy > 40) drawWaterSpray(ctx, ship);
  ctx.fillStyle = 'rgba(230,245,255,.64)'; ctx.font = '11px monospace'; ctx.fillText(`WAVE ${wave}  //  ${enemies.length} HOSTILES`, 24, 812);
}

function drawEnemy(ctx: CanvasRenderingContext2D, enemy: Enemy): void { ctx.save(); ctx.translate(enemy.x, enemy.y); const surface = enemy.kind === 'ship' || enemy.kind === 'dreadnought'; if (enemy.kind === 'dreadnought') { ctx.fillStyle = '#29394c'; ctx.fillRect(-76, -25, 152, 39); ctx.fillStyle = '#637b8d'; ctx.fillRect(-32, -54, 64, 30); ctx.fillStyle = '#f56f63'; [-48, 0, 48].forEach((x) => ctx.fillRect(x, -62, 5, 34)); } else if (enemy.kind === 'ship') { ctx.fillStyle = '#3f5267'; ctx.fillRect(-42, -16, 84, 25); ctx.fillStyle = '#72899a'; ctx.fillRect(-15, -31, 30, 15); ctx.fillStyle = '#fc8068'; ctx.fillRect(12, -38, 4, 24); } else if (enemy.kind === 'mine') { ctx.strokeStyle = '#ffd66b'; ctx.fillStyle = '#3e4559'; ctx.lineWidth = 2; ctx.beginPath(); ctx.arc(0, 0, 15, 0, Math.PI * 2); ctx.fill(); ctx.stroke(); for (let i = 0; i < 8; i++) { const angle = i * Math.PI / 4; ctx.beginPath(); ctx.moveTo(Math.cos(angle) * 15, Math.sin(angle) * 15); ctx.lineTo(Math.cos(angle) * 23, Math.sin(angle) * 23); ctx.stroke(); } } else { ctx.fillStyle = enemy.kind === 'diver' ? '#d89afa' : '#f27878'; ctx.beginPath(); ctx.moveTo(18, 0); ctx.lineTo(-15, -11); ctx.lineTo(-8, 0); ctx.lineTo(-15, 11); ctx.closePath(); ctx.fill(); } ctx.fillStyle = 'rgba(8,15,24,.7)'; ctx.fillRect(-20, surface ? 22 : 20, 40, 4); ctx.fillStyle = enemy.kind === 'dreadnought' ? '#e0a5ff' : '#ffbc72'; ctx.fillRect(-20, surface ? 22 : 20, 40 * enemy.hp / enemy.maxHp, 4); ctx.restore(); }
function drawShot(ctx: CanvasRenderingContext2D, shot: EnemyShot, color: string): void { if (shot.weapon === 'laser' && shot.originX !== undefined && shot.originY !== undefined) { ctx.save(); ctx.strokeStyle = '#a8faff'; ctx.lineWidth = 4; ctx.shadowColor = '#52e9ff'; ctx.shadowBlur = 16; ctx.beginPath(); ctx.moveTo(shot.originX, shot.originY); ctx.lineTo(shot.x, shot.y); ctx.stroke(); ctx.restore(); return; } if (shot.weapon === 'missile') { ctx.save(); ctx.strokeStyle = 'rgba(255,174,92,.55)'; ctx.lineWidth = 3; ctx.beginPath(); ctx.moveTo(shot.x - shot.vx * .08, shot.y - shot.vy * .08); ctx.lineTo(shot.x, shot.y); ctx.stroke(); ctx.fillStyle = '#fff2bc'; ctx.beginPath(); ctx.arc(shot.x, shot.y, 5, 0, Math.PI * 2); ctx.fill(); ctx.restore(); return; } ctx.fillStyle = color; ctx.beginPath(); ctx.arc(shot.x, shot.y, 3.5, 0, Math.PI * 2); ctx.fill(); }
function drawClouds(ctx: CanvasRenderingContext2D): void { const time = performance.now() * .000015; ctx.save(); ctx.fillStyle = 'rgba(225,244,247,.13)'; for (let index = 0; index < 6; index++) { const x = ((index * 265 + time * (22 + index * 5)) % 1450) - 130; const y = 80 + (index % 3) * 110; ctx.beginPath(); ctx.ellipse(x, y, 90, 19, 0, 0, Math.PI * 2); ctx.ellipse(x + 54, y + 8, 65, 15, 0, 0, Math.PI * 2); ctx.fill(); } ctx.restore(); }
function drawWaterSpray(ctx: CanvasRenderingContext2D, ship: GunshipBody): void { ctx.save(); ctx.fillStyle = 'rgba(184,241,250,.6)'; const count = Math.min(22, Math.floor((ship.vy - 35) / 12)); for (let index = 0; index < count; index++) { const x = ship.x + Math.sin(index * 19.7) * (18 + index * 3); const y = SEA_Y - Math.abs(Math.cos(index * 7.3)) * (8 + index * 2); ctx.fillRect(x, y, 2, 2 + index % 3); } ctx.restore(); }
